diff --git a/chrome/browser/browseros/update/browseros_update_manifest.h b/chrome/browser/browseros/update/browseros_update_manifest.h
new file mode 100644
index 0000000000000..0000000000000
--- /dev/null
+++ b/chrome/browser/browseros/update/browseros_update_manifest.h
@@ -0,0 +1,109 @@
+// Copyright 2024 The Chromium Authors
+// Use of this source code is governed by a BSD-style license that can be
+// found in the LICENSE file.
+
+#ifndef CHROME_BROWSER_BROWSEROS_UPDATE_BROWSEROS_UPDATE_MANIFEST_H_
+#define CHROME_BROWSER_BROWSEROS_UPDATE_BROWSEROS_UPDATE_MANIFEST_H_
+
+#include <optional>
+#include <string>
+#include <string_view>
+#include <utility>
+#include <vector>
+
+#include "base/value.h"
+#include "base/version.h"
+#include "url/gurl.h"
+
+namespace browseros_update {
+
+// One downloadable artifact for a single platform.
+struct PlatformEntry {
+  // Absolute https URL of the installer. Guaranteed to be on an
+  // allow-listed host by Manifest::Parse().
+  GURL url;
+
+  // 64 lowercase hex characters. The manifest is untrusted input; a
+  // malformed digest is rejected at parse time rather than at verify time
+  // so a bad manifest never reaches the downloader.
+  std::string sha256;
+
+  // Size in bytes, always > 0.
+  int64_t size = 0;
+
+  // Minimum OS version, e.g. "10.0.17763". Empty means "no constraint".
+  std::string min_os_version;
+
+  // Expected Authenticode publisher subject, e.g. "BrowserOS Ltd".
+  // Empty means publisher pinning is not required for this artifact.
+  std::string publisher;
+};
+
+// A parsed and validated update manifest.
+//
+// The manifest is fetched over plain HTTPS from a public bucket, so every
+// field is treated as hostile until checked here. Parse() enforces the
+// whole contract; nothing downstream re-validates.
+class Manifest {
+ public:
+  // Bump when the wire format changes incompatibly. The client refuses any
+  // manifest it does not recognise rather than guessing.
+  static constexpr int kSchemaVersion = 1;
+
+  // A manifest with this channel is a deliberate kill switch: the client
+  // reports "updates paused" and offers nothing. This is how a bad release
+  // is halted without shipping a new browser build.
+  static constexpr char kChannelPaused[] = "paused";
+
+  // Platform key for the running build, e.g. "windows-x64" or "mac-arm64".
+  // Returns an empty string on platforms we do not update.
+  static std::string CurrentPlatformKey();
+
+  // Parses and validates a manifest for the running platform.
+  // See ParseForPlatform() for the contract and errors.
+  static std::optional<Manifest> Parse(
+      std::string_view json,
+      const std::vector<std::string>& expected_hosts);
+
+  // Same, but for an explicit platform key. Exposed so unit tests can
+  // exercise every platform branch on any host, and so the caller that
+  // already knows the key does not pay for CurrentPlatformKey() twice.
+  static std::optional<Manifest> ParseForPlatform(
+      std::string_view json,
+      const std::vector<std::string>& expected_hosts,
+      const std::string& platform_key);
+
+  // True when this manifest is the kill switch. A paused manifest is
+  // well-formed and must still be served: it is how updates stop.
+  bool IsPaused() const;
+
+  bool IsValid() const { return valid_; }
+
+  const base::Version& version() const { return version_; }
+  const std::string& channel() const { return channel_; }
+  const std::string& notes_url() const { return notes_url_; }
+  const PlatformEntry* GetPlatform(const std::string& key) const;
+  const PlatformEntry* GetPlatformForCurrentBuild() const;
+
+  // Serializes |manifest| the way tools/release/generate_update_manifests.py
+  // does, for Ed25519 signature verification. Must stay in lockstep with
+  // canonical_manifest_bytes() in that script.
+  //
+  // Only valid for manifests whose values are ASCII. Python emits raw
+  // UTF-8 with ensure_ascii=False while base escapes non-ASCII, so the two
+  // forms diverge above U+007F. Manifests generated by our CI are ASCII, and
+  // the signature is optional, so this is a documented restriction rather
+  // than a live bug.
+  static std::string CanonicalizeJsonForSigning(const base::Value::Dict& manifest);
+
+ private:
+  bool valid_ = false;
+  base::Version version_;
+  std::string channel_;
+  std::string notes_url_;
+  std::vector<std::pair<std::string, PlatformEntry>> platforms_;
+};
+
+}  // namespace browseros_update
+
+#endif  // CHROME_BROWSER_BROWSEROS_UPDATE_BROWSEROS_UPDATE_MANIFEST_H_
